require("current.utils")
require("current.base")
-- spec("current.plugins.colorscheme")
-- spec("current.plugins.night-owl")
spec("current.plugins.catppuccin")
spec("current.plugins.treesitter")
spec("current.plugins.treesitter_text_objects")
spec("current.plugins.telescope")
spec("current.plugins.oil")
spec("current.plugins.cloak")
spec("current.plugins.nvim-tree")
spec("current.plugins.mason-lspconfig")
spec("current.plugins.lualine")
spec("current.plugins.whichkey")
spec("current.plugins.lsp-config")
spec("current.plugins.cmp")
spec("current.plugins.obsidian")
require("current.plugins.manager")
